class Knowledge:
    def __init__(self):
        self.depth = {
            'data structures': 0.0,
                'dsu': 0.0,
                'segment tree': 0.0,
                'persistent data structures': 0.0,
                'treap': 0.0,
                'stack': 0.0,
                'queue': 0.0,
                'priority queue': 0.0,
                'hash table': 0.0,
            'game theory': 0.0,
            'geometry': 0.0,
            'graph theory': 0.0,
                'flows': 0.0,
                'shortest path': 0.0,
                    'bfs': 0.0,
                    'Dijkstra algorithm': 0.0,
                    'Floyd–Warshall algorithm': 0.0,
                    'Bellman–Ford algorithm': 0.0,
                'graph matchings': 0.0,
                'trees': 0.0,
                '2-sat': 0.0,
                'MST': 0.0,
                'topological sort': 0.0,
            'string algorithms': 0.0,
                'hashing': 0.0,
                'string suffix structures': 0.0,
                'prefix function': 0.0,
                'z-function': 0.0,
            'dynamic programming': 0.0,
            'math': 0.0,
                'matrices': 0.0,
                'probabilities': 0.0,
                'number theory': 0.0,
                'fft': 0.0,
                'chinese remainder theorem': 0.0,
                'combinatorics': 0.0,
            'greedy': 0.0,
            'two pointers': 0.0,
            'divide and conquer': 0.0,
            'binary search': 0.0,
            'sortings': 0.0,
            'meet-in-the-middle': 0.0,
            'ternary search': 0.0,
            'bitmasks': 0.0,
            'brute force': 0.0,
            'constructive algorithms': 0.0,
        }
